name: flutter_metawear
description: A wrapper that interfaces with Metawear
version: 0.5.0
author: Michael Pollind <polli104@mail.chapman.edu>
homepage: https://github.com/pauldemarco/flutter_blue

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^2.1.1
  sprintf: ^4.0.0
  flutter_blue: ^0.5.0

flutter:
  plugin:
    androidPackage: com.gaitlab.fluttermetawear
    pluginClass: FlutterMetawearPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter